#!/bin/sh
set -e

npm run build

for f in dist/chrome-capture-for-channels-macos-*; do
  codesign --remove-signature $f
done

codesign -s "Developer ID Application: Fancy Bits, LLC (LVM8JB4FT5)" dist/chrome-capture-for-channels-macos-arm64
zip dist/ChromeCaptureARM64.zip dist/chrome-capture-for-channels-macos-arm64

codesign -s "Developer ID Application: Fancy Bits, LLC (LVM8JB4FT5)" dist/chrome-capture-for-channels-macos-x64
zip dist/ChromeCaptureIntel.zip dist/chrome-capture-for-channels-macos-x64

xcrun notarytool submit dist/ChromeCaptureARM64.zip --keychain-profile "fancybot_deployer"
xcrun notarytool submit dist/ChromeCaptureIntel.zip --keychain-profile "fancybot_deployer"
