#!/bin/sh
set -e

rm -rf dist
bun run build

codesign --entitlements entitlements.xml -o runtime -fs "Fancy Bits" dist/cc4c
(cd dist && zip -r ChromeCaptureARM64.zip cc4c)
xcrun notarytool submit dist/ChromeCaptureARM64.zip --keychain-profile "fancybot_deployer"
